// Pocket Dystopia - Trait Data with Mood Tags
// All traits are safe for elementary school classrooms.

const DATA = {
  heroTraits: [
    { text: "found a book, now thinks they are 'The One'", mood: [] },
    { text: "too empathetic for this cruel world", mood: [] },
    { text: "parkour expert (run, jump, repeat)", mood: ["post-apocalyptic"] },
    { text: "can hack the mainframe in under 3 seconds", mood: ["ai-takeover", "corporate"] },
    { text: "rebellious streak (hates beige)", mood: ["corporate"] },
    { text: "obnoxious sense of justice", mood: ["political"] },
    { text: "thinking fast, acting not-so-smart", mood: [] },
    { text: "the 'Chosen One' (Generic Variant B)", mood: [] },
    { text: "has a robot arm or glowy eye", mood: ["ai-takeover"] },
    { text: "super young but somehow can fix everything", mood: [] },
    { text: "must find THE TRUTH (Caps Lock permanently on)", mood: ["political"] },
    { text: "allergic to authority figures", mood: ["political"] },
    { text: "raised by library robots", mood: ["ai-takeover"] },
    { text: "talks to plants (the plants talk back)", mood: ["post-apocalyptic"] },
    { text: "drew a map on a napkin, calls it 'the plan'", mood: [] },
    { text: "can smell danger (it smells like burnt toast)", mood: [] },
    { text: "accidentally started the revolution by sneezing", mood: ["political"] },
    { text: "carries a broken compass for 'good luck'", mood: ["post-apocalyptic"] },
    { text: "has memorized every air duct in the building", mood: ["corporate"] },
    { text: "refuses to use doors (windows only)", mood: [] },
    { text: "makes motivational speeches nobody asked for", mood: ["corporate"] },
    { text: "best friends with every stray animal in the sector", mood: ["post-apocalyptic"] },
    { text: "once read a self-help book, now unstoppable", mood: ["corporate"] },
    { text: "communicates only in dramatic whispers", mood: [] },
    { text: "has a catchphrase they use way too often", mood: [] },
    { text: "sleeps with one eye open (literally, it is glued)", mood: [] },
  ],

  heroWeaknesses: [
    { text: "trusts the villain immediately every time", mood: [] },
    { text: "abandonment issues (classic)", mood: [] },
    { text: "guilt over something in Chapter 1", mood: [] },
    { text: "punches walls when frustrated", mood: [] },
    { text: "physically wobbly but has 'heart'", mood: [] },
    { text: "thinks they are invincible (spoiler: absolutely not)", mood: [] },
    { text: "will sacrifice everything for their pet", mood: [] },
    { text: "cannot follow simple instructions", mood: [] },
    { text: "panics when anything beeps", mood: ["ai-takeover"] },
    { text: "trackable via their microchip", mood: ["ai-takeover", "corporate"] },
    { text: "afraid of the dark (lives underground)", mood: ["post-apocalyptic"] },
    { text: "cannot whisper, only shout-whispers", mood: [] },
    { text: "terrible at lying but tries constantly", mood: [] },
    { text: "allergic to the one thing that could save everyone", mood: [] },
    { text: "always trips at the worst possible moment", mood: [] },
    { text: "gets distracted by shiny objects mid-mission", mood: [] },
    { text: "overshares personal feelings during battle", mood: [] },
    { text: "refuses to ask for directions, gets lost in every sector", mood: ["post-apocalyptic"] },
    { text: "believes every disguise works (none do)", mood: ["political"] },
    { text: "cannot remember anyone's name correctly", mood: [] },
  ],

  heroTraumas: [
    { text: "parents taken away by mysterious masked figures", mood: ["political"] },
    { text: "house blew up (character building, apparently)", mood: ["post-apocalyptic"] },
    { text: "boarding school for 'difficult' children", mood: ["political"] },
    { text: "skipped breakfast this morning (devastating)", mood: [] },
    { text: "exiled for having non-regulation hair", mood: ["corporate"] },
    { text: "grew up in a bubble (literally)", mood: [] },
    { text: "accidentally snitched once, never lived it down", mood: ["political"] },
    { text: "survived the 'Great Purge of Snacks'", mood: ["political"] },
    { text: "brainwashed by TV commercials", mood: ["corporate"] },
    { text: "tested on like a lab hamster", mood: ["ai-takeover"] },
    { text: "favorite toy was confiscated by the regime", mood: ["political"] },
    { text: "won a contest but the prize was a trap", mood: [] },
    { text: "their goldfish was 'relocated' by the government", mood: ["political"] },
    { text: "told they were special, then put on a waiting list", mood: ["corporate"] },
    { text: "watched their treehouse get demolished for a parking lot", mood: ["corporate"] },
    { text: "assigned a 'happiness score' of 2 out of 10", mood: ["ai-takeover"] },
    { text: "their lunchbox was classified as contraband", mood: ["political"] },
    { text: "made Employee of the Month but the company was evil", mood: ["corporate"] },
    { text: "pen pal turned out to be a surveillance bot", mood: ["ai-takeover"] },
    { text: "birthday party was canceled due to 'resource allocation'", mood: ["corporate"] },
  ],

  villainTraits: [
    { text: "chad dictator with great hair", mood: ["political"] },
    { text: "a corrupted leader who took control of the entire city", mood: ["political"] },
    { text: "tech-bro uploading brains to the cloud (no refunds)", mood: ["ai-takeover", "corporate"] },
    { text: "angry general shouting at screens all day", mood: ["political"] },
    { text: "CEO of Water (subscription required)", mood: ["corporate"] },
    { text: "scientist who says 'I am saving humanity by destroying it'", mood: ["ai-takeover"] },
    { text: "an evil robot who wants to destroy the world (classic)", mood: ["ai-takeover"] },
    { text: "politician hiding aliens in the basement", mood: ["political"] },
    { text: "an alien emperor who wants to take over the planet", mood: [] },
    { text: "AI who decided saving humanity means rebooting it", mood: ["ai-takeover"] },
    { text: "the giant dragon who is, for some reason, always the bad guy", mood: [] },
    { text: "principal who banned recess permanently", mood: [] },
    { text: "billionaire who bought the sun", mood: ["corporate"] },
    { text: "evil twin who is slightly taller", mood: [] },
    { text: "former hall monitor who never gave up the power", mood: ["political"] },
    { text: "inventor of the homework machine (mandatory use)", mood: ["ai-takeover"] },
    { text: "runs the only pizza place in town, charges outrageous prices", mood: ["corporate"] },
    { text: "controls the weather app (always says 'rain')", mood: ["ai-takeover"] },
    { text: "librarian who banned all books except their own", mood: ["political"] },
    { text: "self-appointed king of the school cafeteria", mood: [] },
    { text: "mad scientist whose experiments keep 'accidentally' escaping", mood: [] },
    { text: "the neighbor who reports everyone for everything", mood: ["political"] },
    { text: "influencer with mind-control followers", mood: ["ai-takeover", "corporate"] },
    { text: "wizard who graduated from an online magic school", mood: [] },
    { text: "time-traveler who keeps making things worse", mood: [] },
    { text: "a very polite villain who apologizes before every evil deed", mood: [] },
  ],

  villainWeaknesses: [
    { text: "monologues their evil plan every time", mood: [] },
    { text: "forgot about the Power of Friendship", mood: [] },
    { text: "forgot to update the firewall", mood: ["ai-takeover"] },
    { text: "minions are forming a union", mood: ["corporate"] },
    { text: "obsessed with symmetry", mood: [] },
    { text: "fragile ego (hates bad reviews)", mood: ["corporate"] },
    { text: "actually three kids in a trench coat", mood: [] },
    { text: "secretly a fan of the hero's cooking", mood: [] },
    { text: "hiding a very silly hat collection", mood: [] },
    { text: "relies on outdated technology", mood: ["ai-takeover"] },
    { text: "cannot resist petting cute animals", mood: [] },
    { text: "falls asleep during their own speeches", mood: ["political"] },
    { text: "allergic to their own secret weapon", mood: [] },
    { text: "keeps a diary that anyone could find", mood: [] },
    { text: "terrified of pigeons", mood: [] },
    { text: "their evil lair has terrible WiFi", mood: ["ai-takeover"] },
    { text: "gets homesick easily", mood: [] },
    { text: "cannot operate the coffee machine", mood: ["corporate"] },
    { text: "trips over their own cape regularly", mood: [] },
    { text: "gets emotional during sad movies", mood: [] },
  ],

  squadMembers: [
    { text: "loyal but terrified (Red Shirt number 1)", mood: [] },
    { text: "secretly in the resistance (has a cool tattoo to prove it)", mood: ["political"] },
    { text: "annoyingly optimistic despite acid rain", mood: ["post-apocalyptic"] },
    { text: "scavenger who hoards spoons for no reason", mood: ["post-apocalyptic"] },
    { text: "ex-government worker who keeps saying 'I should not say this but...'", mood: ["political"] },
    { text: "medic who uses questionable bandages", mood: ["post-apocalyptic"] },
    { text: "elder who says 'I remember trees...'", mood: ["post-apocalyptic"] },
    { text: "tech-kid who fixes everything with chewing gum", mood: ["ai-takeover"] },
    { text: "silent brooding type (budget reasons)", mood: [] },
    { text: "citizen who actually reads the Terms of Service", mood: ["corporate"] },
    { text: "the musician who is completely tone deaf", mood: [] },
    { text: "conspiracy theorist who is right about one thing", mood: ["political"] },
    { text: "robot who thinks it is human (nobody corrects it)", mood: ["ai-takeover"] },
    { text: "chef who can make anything taste okay-ish", mood: ["post-apocalyptic"] },
    { text: "navigator who only knows left turns", mood: [] },
    { text: "historian who won't stop saying 'actually...'", mood: [] },
    { text: "the one who always has snacks (very popular)", mood: [] },
    { text: "hacker who only knows one password", mood: ["ai-takeover"] },
    { text: "lookout who needs glasses badly", mood: [] },
    { text: "former villain intern who switched sides", mood: [] },
    { text: "translator who makes up half the translations", mood: [] },
    { text: "pet that is probably smarter than everyone", mood: [] },
    { text: "mechanic who 'fixes' things with a hammer", mood: [] },
    { text: "the squad's self-appointed morale officer", mood: [] },
    { text: "expert in a skill nobody has ever needed until now", mood: [] },
    { text: "someone who just showed up and nobody knows why", mood: [] },
  ],

  settings: [
    { text: "Sector 7 (it is always Sector 7)", mood: ["post-apocalyptic"] },
    { text: "the tunnels (smells like wet dog)", mood: ["post-apocalyptic"] },
    { text: "Zone A versus Zone Z", mood: ["political"] },
    { text: "Cloud City (oxygen subscription required)", mood: ["corporate"] },
    { text: "a rustic city that looks suspiciously like a movie set", mood: [] },
    { text: "Radioactive Forest of Mild Danger", mood: ["post-apocalyptic"] },
    { text: "rickety bridges between abandoned skyscrapers", mood: ["post-apocalyptic"] },
    { text: "spooky laboratory with flickering lights", mood: ["ai-takeover"] },
    { text: "Too Cold To Live: The City", mood: ["post-apocalyptic"] },
    { text: "underground bunker number 404", mood: ["post-apocalyptic"] },
    { text: "the high-tech lab that somehow always leaks", mood: ["ai-takeover"] },
    { text: "a shopping mall that has been 'temporarily closed' for 50 years", mood: ["corporate"] },
    { text: "the last library (guarded by feral librarians)", mood: [] },
    { text: "a floating school bus that nobody can steer", mood: [] },
    { text: "an amusement park where nothing is amusing", mood: ["corporate"] },
    { text: "the cafeteria to end all cafeterias", mood: [] },
    { text: "a factory that only makes beige uniforms", mood: ["corporate"] },
    { text: "someone's attic, converted into rebel headquarters", mood: ["political"] },
    { text: "a zoo where the animals run the place", mood: [] },
    { text: "the internet, but it is a physical place now", mood: ["ai-takeover"] },
    { text: "a desert made entirely of recycled homework", mood: [] },
    { text: "a train that never stops (bathroom breaks are complicated)", mood: [] },
    { text: "a greenhouse the size of a small country", mood: ["post-apocalyptic"] },
    { text: "the rooftop garden above the villain's headquarters", mood: [] },
    { text: "a submarine made from recycled soda cans", mood: ["post-apocalyptic"] },
    { text: "a cave with surprisingly good interior decorating", mood: [] },
  ],

  times: [
    { text: "Tuesday, next week (economy is bad)", mood: ["corporate"] },
    { text: "2099 (everything is chrome now)", mood: ["ai-takeover"] },
    { text: "the Year of Our AI Overlord", mood: ["ai-takeover"] },
    { text: "after the Super-Flu, nobody remembers when exactly", mood: ["post-apocalyptic"] },
    { text: "100 years after aliens pointed and laughed at us", mood: [] },
    { text: "day 1 of the New Regime (orientation day)", mood: ["political"] },
    { text: "a timeline confusingly similar to right now", mood: [] },
    { text: "the Age of Beige Uniforms", mood: ["corporate"] },
    { text: "Mars o'clock (Earth is a parking lot)", mood: ["post-apocalyptic"] },
    { text: "alternate 1985 (everything went differently)", mood: [] },
    { text: "exactly 5 minutes in the future", mood: [] },
    { text: "the year homework became illegal", mood: [] },
    { text: "after the Great Wi-Fi Outage", mood: ["ai-takeover"] },
    { text: "when dinosaurs came back (they are not happy)", mood: [] },
    { text: "the summer that lasted three years straight", mood: ["post-apocalyptic"] },
    { text: "right after nap time was canceled globally", mood: ["political"] },
    { text: "the moment someone pressed the big red button", mood: [] },
    { text: "back when pizza was still free (the golden age)", mood: ["corporate"] },
    { text: "three days before the robots figure it out", mood: ["ai-takeover"] },
    { text: "during the longest Monday in recorded history", mood: ["corporate"] },
  ],

  obstacles: [
    { text: "drones with really bad aim", mood: ["ai-takeover"] },
    { text: "acid rain but more of a drizzle", mood: ["post-apocalyptic"] },
    { text: "top 10 Anime-Style Betrayals", mood: [] },
    { text: "vending machine is out of water again", mood: ["corporate"] },
    { text: "road closed (construction forever and ever)", mood: [] },
    { text: "the timer is ticking on something important", mood: [] },
    { text: "Mom calls via hologram to guilt trip", mood: ["ai-takeover"] },
    { text: "the important gadget jammed at the worst moment", mood: [] },
    { text: "existential dread (the invisible enemy)", mood: [] },
    { text: "the rabbit chewed through the important cable", mood: [] },
    { text: "elevator music that never, ever stops", mood: ["corporate"] },
    { text: "a riddle that makes absolutely no sense", mood: [] },
    { text: "the bridge is a drawbridge and nobody has the crank", mood: ["post-apocalyptic"] },
    { text: "quicksand but it is actually just very sticky mud", mood: ["post-apocalyptic"] },
    { text: "an alarm that will not stop beeping", mood: ["ai-takeover"] },
    { text: "the map is upside down (or is the world upside down?)", mood: [] },
    { text: "allergies acting up at the worst moment", mood: [] },
    { text: "a pop quiz in the middle of the escape", mood: [] },
    { text: "the getaway vehicle needs to be charged for 8 hours", mood: ["ai-takeover"] },
    { text: "someone forgot the secret password", mood: ["ai-takeover"] },
    { text: "the villain's pet is blocking the only exit", mood: [] },
    { text: "a very long line with no skip option", mood: ["corporate"] },
    { text: "gravity keeps switching directions", mood: [] },
    { text: "the instruction manual is in a language nobody speaks", mood: [] },
    { text: "an unexpected field trip to the danger zone", mood: [] },
  ],
};
